### PR TITLE
feat: show images from Bard's reply

### PR DESCRIPTION
**Pull request by handsome0hell**

### CODE REVIEW

**Comment by F33RNI** [comment]
Everything works for me regarding the generation of images by the Bard (except for the need to fix `md2tgmd`)

**Comment by F33RNI** [comment]
Bing Image Generator stopped working for me
```
Traceback (most recent call last):
  File "/home/fern/GPT-Telegramus/BotHandler.py", line 197, in send_message_async
    await _send_text_async_split(config, messages[lang], request_response, end)
  File "/home/fern/GPT-Telegramus/BotHandler.py", line 280, in _send_text_async_split
    = request_response.response[response_part_index_start:response_part_index_stop].strip()
AttributeError: 'list' object has no attribute 'strip'
```
Error is here
```python
response_part \
            = request_response.response[response_part_index_start:response_part_index_stop].strip()
```

**Comment by handsome0hell** [comment]
> Bing Image Generator stopped working for me

I tried to fix it. I can't use Bing on my server, so I didn't test this. I'm sorry.

**Comment by F33RNI** [comment]
🙃🙃🙃
```
Traceback (most recent call last):
  File "/home/fern/GPT-Telegramus/BotHandler.py", line 198, in send_message_async
    await _send_text_async_split(config, messages[lang], request_response, end)
  File "/home/fern/GPT-Telegramus/BotHandler.py", line 269, in _send_text_async_split
    (await asyncio.gather(*[parse_img(img)
  File "/home/fern/GPT-Telegramus/BotHandler.py", line 236, in parse_img
    img = Image.open(io.BytesIO(res.content))
  File "/home/fern/GPT-Telegramus/venv/lib/python3.10/site-packages/PIL/Image.py", line 3305, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f1b0e0d53f0>
```

**Comment by F33RNI** [comment]
Pls wait, I'll trying to fix it now

**Comment by handsome0hell** [comment]
> 🙃🙃🙃
> 
> ```
> Traceback (most recent call last):
>   File "/home/fern/GPT-Telegramus/BotHandler.py", line 198, in send_message_async
>     await _send_text_async_split(config, messages[lang], request_response, end)
>   File "/home/fern/GPT-Telegramus/BotHandler.py", line 269, in _send_text_async_split
>     (await asyncio.gather(*[parse_img(img)
>   File "/home/fern/GPT-Telegramus/BotHandler.py", line 236, in parse_img
>     img = Image.open(io.BytesIO(res.content))
>   File "/home/fern/GPT-Telegramus/venv/lib/python3.10/site-packages/PIL/Image.py", line 3305, in open
>     raise UnidentifiedImageError(msg)
> PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f1b0e0d53f0>
> ```

I need the image links from Bing to identify this problem.

**Comment by F33RNI** [comment]
> > 🙃🙃🙃
> > ```
> > Traceback (most recent call last):
> >   File "/home/fern/GPT-Telegramus/BotHandler.py", line 198, in send_message_async
> >     await _send_text_async_split(config, messages[lang], request_response, end)
> >   File "/home/fern/GPT-Telegramus/BotHandler.py", line 269, in _send_text_async_split
> >     (await asyncio.gather(*[parse_img(img)
> >   File "/home/fern/GPT-Telegramus/BotHandler.py", line 236, in parse_img
> >     img = Image.open(io.BytesIO(res.content))
> >   File "/home/fern/GPT-Telegramus/venv/lib/python3.10/site-packages/PIL/Image.py", line 3305, in open
> >     raise UnidentifiedImageError(msg)
> > PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f1b0e0d53f0>
> > ```
> 
> I need the image links from Bing to identify this problem.

Saving images locally is also not good. Telegram can accept links as input. The only thing we need to do is avoid the `.svg` file. Also, we need to fix the data saver (there is no check that response is image). So, please wait, I’ll trying to fix this now

**Comment by handsome0hell** [comment]
> Saving images locally is also not good. Telegram can accept links as input. The only thing we need to do is avoid the `.svg` file. Also, we need to fix the data saver (there is no check that response is image). So, please wait, I’ll trying to fix this now

The problem I'm facing is that some links returned from Bard are not valid images or supported image formats. Maybe we can use `requests.head` to check the MEME type of link. But still, if the image URL is not valid, telegram will reject the whole message.

**Comment by handsome0hell** [comment]
> ```PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f1b0e0d53f0>```

Fixed. Tested on my local machine.

**Comment by F33RNI** [comment]
Now i'm getting responses from Bard like this 🙃

*Me:*
Hi! Please draw a Cat

*Bard:*
Sure, here is the graph:
[image-tag: code_execution_image_1_1702148263.9369574.png]

**Comment by handsome0hell** [comment]
> _Bard:_ Sure, here is the graph: [image-tag: code_execution_image_1_1702148263.9369574.png]

It seems like the image source from Bard blocked access from a bot. I'm trying to add User-Agent for requests, which seems to work.

I'm fixing the problem, which image might be too big. I will push my code later.

**Comment by F33RNI** [comment]
I've updated a few things including image logging. Tested on Bard and BingImageGen

**Comment by F33RNI** [comment]
> > _Bard:_ Sure, here is the graph: [image-tag: code_execution_image_1_1702148263.9369574.png]
> 
> It seems like the image source from Bard blocked access from a bot. I'm trying to add User-Agent for requests, which seems to work.
> 
> I'm fixing the problem, which image might be too big. I will push my code later.

Ok I'll wait until u fix `image-tag` response from Bard

**Review by F33RNI — COMMENTED** [review]
Excellent solution for checking image format 👍

**Comment by handsome0hell** [comment]
> Hi! Please draw a Cat

I tested your prompt and got the same answer. The Bard API didn't send us any images.

image

This is the result from the Bard website. I don't think we can support this now.

**Comment by F33RNI** [comment]
Maybe these graphs have base url to retrieve these type of images `code_execution_image_1_1702148263.9369574.png` ?

**Comment by handsome0hell** [comment]
```json
{
  "content": "Sure, here is the graph:\n[image-tag: code_execution_image_1_1702151707.76185.png]",
  "conversation_id": "c_b1ce829e646419c2",
  "response_id": "r_36009817021c94c2",
  "factuality_queries": null,
  "text_query": "",
  "choices": [
    {
      "id": "rc_1bee96994a572ecc",
      "content": [
        "Sure, here is the graph:\n[image-tag: code_execution_image_1_1702151707.76185.png]"
      ]
    }
  ],
  "links": [
    "https://lh3.googleusercontent.com/bard/AL4VpuO_LqC_HH8q4ODUXBxrX3LVGQZ846eEEBKA7nDEMS8fFSvL6MBUmg87qeSq4X54UsmAHGgTzKQVFsJIXGSUrIebaWPgOZenNvxZNwG_tLTM-15zylBp3FD0xt4-Zvl6rqkpBRdcRNZ9rdY8PWBa3IrXDJAJ2z3Cy5jmDSSeQX9pHM7me3xH1e7nVvPLfJdYGzXQZ5kwAi2W1us0lDfonIe9cAq-cdcOTkDEkWDQimMGARl2HBCdk-bBIg9aQe68KokSjAviTJs3Nl3HR1yxgf2FMtSL1JI6J5FZoW97KFVVIv_TRrRg1pCxOYVUuQT6cvyPNeI1EvxVRNaA-Ls"
  ],
  "images": [],
  "program_lang": null,
  "code": null,
  "status_code": 200
}
```

Here is the response from Bard. As you can see, the image URL is in the `links` list. The content is unrelated to the `image-tag`. Maybe we can use `links` instead of `images`?

**Comment by F33RNI** [comment]
Can we retrieve images from them?

**Comment by handsome0hell** [comment]
> Can we retrieve images from them?

I can do that from my browser. It seems it needs my cookies to access the URL.
I suggest that we should just ignore this situation. These images is not that useful...

**Comment by F33RNI** [comment]
OK
Then can I merge now?

**Comment by handsome0hell** [comment]
> OK Then can I merge now?

Yes

**Review by F33RNI — APPROVED** [review]

**Pull request merged**
