### PR TITLE
Add indonesian language

### PR DESCRIPTION
**Pull request by wahitftry**

### CODE REVIEW

**Review by F33RNI — CHANGES_REQUESTED** [review]
Thx for your contribution! Please add yourself as a contributor (3️⃣) and I'll merge it

**Comment by wahitftry** [comment]
done

**Comment by F33RNI** [comment]
Please ALWAYS add new languages only to the end of the message file. The language selection is coded in such a way that it is a JSON array. And if you add it to the wrong place, users start to see wrong language instead of previously selected one

**Review by F33RNI — CHANGES_REQUESTED** [review]
Please move your language to the very end of the file. Because for current users, with the 2nd language previously selected, yours will begin to be displayed.

**Review by F33RNI — APPROVED** [review]

**Comment by F33RNI** [comment]
I'll post a new release soon. Thx!

**Pull request merged**
